"""empty message

Revision ID: 816afd646529
Revises: 904cac27cd2e
Create Date: 2021-05-21 17:30:44.573967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816afd646529'
down_revision = '904cac27cd2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('task', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_time', sa.String(length=128), nullable=True),
    sa.Column('urgency', sa.String(length=128), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=128), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('newcol', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_end_time'), 'todos', ['end_time'], unique=False)
    op.create_index(op.f('ix_todos_name'), 'todos', ['name'], unique=False)
    op.create_index(op.f('ix_todos_starting_time'), 'todos', ['starting_time'], unique=False)
    op.create_index(op.f('ix_todos_task'), 'todos', ['task'], unique=False)
    op.create_index(op.f('ix_todos_urgency'), 'todos', ['urgency'], unique=False)
    op.drop_index('ix_todo_end_time', table_name='todo')
    op.drop_index('ix_todo_name', table_name='todo')
    op.drop_index('ix_todo_starting_time', table_name='todo')
    op.drop_index('ix_todo_task', table_name='todo')
    op.drop_index('ix_todo_urgency', table_name='todo')
    op.drop_table('todo')
    op.add_column('posts', sa.Column('related_todo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'todos', ['related_todo'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'related_todo')
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('task', sa.VARCHAR(length=128), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('starting_time', sa.VARCHAR(length=128), nullable=True),
    sa.Column('urgency', sa.VARCHAR(length=128), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('completion_time', sa.DATETIME(), nullable=True),
    sa.Column('newcol', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_todo_urgency', 'todo', ['urgency'], unique=False)
    op.create_index('ix_todo_task', 'todo', ['task'], unique=False)
    op.create_index('ix_todo_starting_time', 'todo', ['starting_time'], unique=False)
    op.create_index('ix_todo_name', 'todo', ['name'], unique=False)
    op.create_index('ix_todo_end_time', 'todo', ['end_time'], unique=False)
    op.drop_index(op.f('ix_todos_urgency'), table_name='todos')
    op.drop_index(op.f('ix_todos_task'), table_name='todos')
    op.drop_index(op.f('ix_todos_starting_time'), table_name='todos')
    op.drop_index(op.f('ix_todos_name'), table_name='todos')
    op.drop_index(op.f('ix_todos_end_time'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
