"""empty message

Revision ID: 84146619a769
Revises: 4e5791862666
Create Date: 2021-05-23 18:31:58.298358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84146619a769'
down_revision = '4e5791862666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('task', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_time', sa.String(length=128), nullable=True),
    sa.Column('urgency', sa.String(length=128), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=128), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('newcol', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_end_time'), 'todos', ['end_time'], unique=False)
    op.create_index(op.f('ix_todos_name'), 'todos', ['name'], unique=False)
    op.create_index(op.f('ix_todos_starting_time'), 'todos', ['starting_time'], unique=False)
    op.create_index(op.f('ix_todos_task'), 'todos', ['task'], unique=False)
    op.create_index(op.f('ix_todos_urgency'), 'todos', ['urgency'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('related_todo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_todo'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_todos_urgency'), table_name='todos')
    op.drop_index(op.f('ix_todos_task'), table_name='todos')
    op.drop_index(op.f('ix_todos_starting_time'), table_name='todos')
    op.drop_index(op.f('ix_todos_name'), table_name='todos')
    op.drop_index(op.f('ix_todos_end_time'), table_name='todos')
    op.drop_table('todos')
    op.drop_table('roles')
    # ### end Alembic commands ###
